Italian/config/routes.rb
Rails.application.routes.draw do

  get '/dining_in' =>'diningin#dining_in'

  root to: 'home#index'

  get 'home' => 'home#index'

  get 'post' => 'post#index'

  resources :posts

  get 'contact' => 'contact#index'

  get 'family' => 'family#index'

  get 'event' => 'event#index'

end

Italian/app/models/post.rb
class Post < ActiveRecord::Base
end

Italian/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Italian/app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def index
	end
end

Italian/app/controllers/diningin_controller.rb
class DininginController < ApplicationController
	def dining_in
	end
end

Italian/app/controllers/event_controller.rb
class EventController < ApplicationController
	def index
	end
end

Italian/app/controllers/family_controller.rb
class FamilyController < ApplicationController
	def index
	end
end

Italian/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Italian/app/controllers/post_controller.rb
class PostController < ApplicationController
	def index 
		@index = Post.all
	end
	def new
		@post = Post.new
	end
end

Italian/app/helpers/application_helper.rb
module ApplicationHelper
end

Italian/app/views/contact/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="col-md-6 mappp" >
	<div id="map" style='width: 500px; height: 300px;'></div>

	<script type="text/javascript" >
		handler = Gmaps.build('Google');
		handler.buildMap({ 
			provider: {
				disableDefaultUI: false
			}, 
			internal: {
				id: 'map'
			}
		}, 
			function(){
		  		markers = handler.addMarkers([
		    {
		      "lat": -33.928619,
		      "lng": 18.410740,
		      "picture": {
		        "url": "assets/map_marker.png",
		        "width":  20,
		        "height": 32
		      },
		      "infowindow": "Piazza Italia"
		    }
		  ]);
		  handler.bounds.extendWith(markers);
		  handler.fitMapToBounds();
		  handler.getMap().setZoom(17);
		});
	</script>
</div>

<div class="col-md-6 contact_info">
	<p id="address">
		2 MLT House Park Road Gardens <br>
		Cape Town, Western Cape
	</p>
	<p id="phone">
		Call us at <a href="callto:0214245025">021 424 5025</a>
	</p>
	<p id="social_media">
		<%= link_to image_tag("facebook_logo.png", :class => "fbpic"), "https://www.facebook.com/piazzaitaliacpt", :target => "_blank" %>
		<%= link_to image_tag("twitter_logo.jpeg", :class => "twitpic"), "https://twitter.com/PiazzaItaliaCpt", :target => "_blank" %>
	</p>

</div>

Italian/app/views/diningin/dining_in.html.erb
<h2 id="page_title"><%= "Our Philosophy" %></h2> <br><br>

<p id="philosophy_text"><%= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio." %></p> <br><br>

<div class="col-lg-4 pic" id="pizza_pic"> 
	<div class="col-md-12 text" id="pizza_text"> 
		<span>I love eating pizza YUMMY!!!!!!</span>
	</div> 
</div>

<div class="col-lg-4 pic" id="pasta_pic"> 
	<div class="col-md-12 text" id="pasta_text"> 
		WOW BEST PASTA EVER HOLY COW
	</div> 
</div>

<div class="col-lg-4 pic" id="shrimp_pic"> 
	<div class="col-md-12 text" id="shrimp_text"> 
		these little dudes are cute and now they're on my pasta
	</div> 
</div>

Italian/app/views/event/index.html.erb
Interested in having your event at Piazza Italia?<br>
Contact Theresa Pearman at <%= mail_to "aivener2012@gmail.com" %>

Italian/app/views/family/index.html.erb
<h2 id="title">The Piazza Italia Family</h2>


<ul id="family">
	<li>
		 <%= image_tag 'face1.jpeg' %>
		 <h2>Leah Procopi</h2>
		 <div>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		 </div>
	</li>

		<li>
		 <%= image_tag 'face2.jpeg' %>
		 <h2>Cameron Cross</h2>
		 <div>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		 </div>
	</li>

		<li>
		 <%= image_tag 'face3.jpeg' %>
		 <h2>Allie Ivener</h2>
		 <div>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		 </div>
	</li>
</ul>

Italian/app/views/home/index.html.erb
<ul class = "slider">
	<li><%= link_to image_tag "carousel_1.jpg", class: "carousel" %></li>
	<li><%= link_to image_tag "carousel_2.jpg", class: "carousel" %></li>
	<li><%= link_to image_tag "carousel_3.jpg", class: "carousel" %></li>
	<li><%= link_to image_tag "carousel_4.jpg", class: "carousel" %></li>
</ul>
<h4>Our Motto</h4>

<h2>Our Story</h2>
	<p class = "body_of_story">
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum velit eu purus dictum, vitae fringilla quam congue. Duis commodo ut ipsum in interdum. Proin ut massa sit amet odio mollis egestas. Cras malesuada, orci vel gravida ultricies, erat mi convallis urna, adipiscing convallis odio orci sed purus. Nunc quis auctor nisi, eu iaculis nulla. Quisque vestibulum tincidunt nibh a tincidunt. Donec laoreet dignissim dolor et pulvinar. Fusce accumsan eget metus vitae rhoncus. Pellentesque nec dictum erat. Suspendisse potenti. Vestibulum vel quam eu odio tempus ullamcorper eu ut eros. Maecenas nulla massa, sagittis ut molestie sit amet, tempus sit amet arcu. Etiam et posuere eros, in fermentum purus. Sed ornare metus a arcu sagittis aliquet quis at lacus. Phasellus libero dui, posuere eget nulla a, egestas dapibus augue. Aenean dictum dolor massa, eu tempor est porttitor in.
	</p>

Italian/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Italian</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 class = "logo_and_name">(Logo) Piazza Italia</h1>
<div class="row nav_bar">
		<div class="col-md-2 header_links"><%= link_to 'Home', home_path, :class => "link_words" %></div>
		<div class="col-md-2 header_links"><%= link_to 'Dining In', dining_in_path, :class => "link_words" %></div>
		<div class="col-md-2 header_links"><%= link_to 'Our Family', family_path, :class => "link_words"  %></div>
		<div class="col-md-2 header_links"><%= link_to 'Events', event_path, :class => "link_words" %></div>
		<div class="col-md-2 header_links"><%= link_to 'Reviews', post_path, :class => "link_words" %></div>
		<div class="col-md-2 header_links"><%= link_to 'Contact Us', contact_path, :class => "link_words" %></div>
</div>

<div class = 'container'>

<%= yield %>

</div>

</body>
</html>

Italian/app/views/post/index.html.erb
<h2> Add Reviews About Piazza Italia </h2>

Italian/app/views/post/new.html.erb
 <div class="form_text">
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="form_text">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="form_text">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>